services:
  - type: web
    name: agri-fastapi
    env: python
    branch: ml
    buildCommand: pip install -r requirements.txt
    startCommand: ./crop\ recommendation/start.sh
    envVars:
      - key: PORT
        value: 10000
    runtime: python
    pythonVersion: 3.10.11
