services:
  - type: web
    name: agri-fastapi
    env: python
    pythonVersion: 3.10.11
    branch: ml
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn CROP_RECOMMENDATION.main:app --host=0.0.0.0 --port=${PORT}
    envVars:
      - key: PORT
        value: 10000
