services:
  - type: web
    name: farmplanner-api
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: bash FARMPLANNER/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
